version: '2'
services:
  zuulserver:
    image: citadel/tmx-zuulsvr:v10
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:        "8761"
      ZIPKIN_URI: "http://zipkin/"
      ZIPKIN_PORT: "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
