#server:
#  port: 8762
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/kelleherke/citadelconfigsvr/
#          searchPaths: zuulservice
          
server:
  port: 8762
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: classpath:config/,classpath:config/zuulservice,classpath:config/addressservice,classpath:config/pupilservice          
          

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/              